# Generated by Django 4.2.2 on 2023-07-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_evento_usuario_alter_evento_data_da_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.TextField(blank=True, null=True, verbose_name='Local do Evento'),
        ),
    ]
